# NUMPY


Numpy is a fundamental library for scientific computing in python . It provides supports for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [120]:
import numpy as np

##  Number of approaches to create an object of ndarray

To create an object of ndarray . We have many approaches 

                    1. array()
                    2. arange()
                    3. zeros()
                    4. ones()
                    5. full()
                    6. linspace()
                    7. eye()
                    8. identity()
                    9. hsatck()
                    10. vstack()

## ndarray object attributes 

 Here  ndarray object contains the following attributes 
 
                  1. dtype
                  2. ndim 
                  3. shape
                  4. size
                  5. itemsize

### create ndarry object using array()

In [121]:
# create 1D array 
arr1 = np.array([1,2,3,4,5])
print("*"*50)
print("Array 1:- " , arr1)
print("Data Type of array 1:- " , arr1.dtype) 
print("Dimension of array 1:- ", arr1.ndim )
print("Size of array 1 :- ", arr1.size)
print("Item size of array1 :-" , arr1.itemsize)
print("*"*50)

**************************************************
Array 1:-  [1 2 3 4 5]
Data Type of array 1:-  int64
Dimension of array 1:-  1
Size of array 1 :-  5
Item size of array1 :- 8
**************************************************


In [122]:
# create 2D array 
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("*"*50)
print("Array 1:- \n " , arr1)
print("Data Type of array 1:- " , arr1.dtype) 
print("Dimension of array 1:- ", arr1.ndim )
print("Size of array 1 :- ", arr1.size)
print("Item size of array1 :-" , arr1.itemsize)
print("*"*50)

**************************************************
Array 1:- 
  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Data Type of array 1:-  int64
Dimension of array 1:-  2
Size of array 1 :-  10
Item size of array1 :- 8
**************************************************


In [123]:
# create 3D array 
arr1 = np.array([[[1,2,3,4,5],[6,7,8,9,10]] , [[10,20,30,40,50],[60,70,80,90,100]]])
print("*"*50)
print("Array 1:- \n " , arr1)
print("Data Type of array 1:- " , arr1.dtype) 
print("Dimension of array 1:- ", arr1.ndim )
print("Size of array 1 :- ", arr1.size)
print("Item size of array1 :-" , arr1.itemsize)
print("*"*50)

**************************************************
Array 1:- 
  [[[  1   2   3   4   5]
  [  6   7   8   9  10]]

 [[ 10  20  30  40  50]
  [ 60  70  80  90 100]]]
Data Type of array 1:-  int64
Dimension of array 1:-  3
Size of array 1 :-  20
Item size of array1 :- 8
**************************************************


### Create ndarray object using arange()

In [124]:
# create 1d array 
arr2 = np.arange(10)
print("*"*50)
print("Array 2:- \n " , arr2)
print("Data Type of array 2:- " , arr2.dtype) 
print("Dimension of array 2:- ", arr2.ndim )
print("Size of array 2 :- ", arr2.size)
print("Item size of array 2 :-" , arr2.itemsize)
print("*"*50)

**************************************************
Array 2:- 
  [0 1 2 3 4 5 6 7 8 9]
Data Type of array 2:-  int64
Dimension of array 2:-  1
Size of array 2 :-  10
Item size of array 2 :- 8
**************************************************


In [125]:
# create 2d array 
arr2 = np.arange(10).reshape(2,5)
print("*"*50)
print("Array 2:- \n " , arr2)
print("Data Type of array 2:- " , arr2.dtype) 
print("Dimension of array 2:- ", arr2.ndim )
print("Size of array 2 :- ", arr2.size)
print("Item size of array 2 :-" , arr2.itemsize)
print("*"*50)

**************************************************
Array 2:- 
  [[0 1 2 3 4]
 [5 6 7 8 9]]
Data Type of array 2:-  int64
Dimension of array 2:-  2
Size of array 2 :-  10
Item size of array 2 :- 8
**************************************************


In [126]:
# create 3d array 
arr2 = np.arange(10,100,3).reshape(3,2,5)
print("*"*50)
print("Array 2:- \n " , arr2)
print("Data Type of array 2:- " , arr2.dtype) 
print("Dimension of array 2:- ", arr2.ndim )
print("Size of array 2 :- ", arr2.size)
print("Item size of array 2 :-" , arr2.itemsize)
print("*"*50)

**************************************************
Array 2:- 
  [[[10 13 16 19 22]
  [25 28 31 34 37]]

 [[40 43 46 49 52]
  [55 58 61 64 67]]

 [[70 73 76 79 82]
  [85 88 91 94 97]]]
Data Type of array 2:-  int64
Dimension of array 2:-  3
Size of array 2 :-  30
Item size of array 2 :- 8
**************************************************


### Create ndarray object using zeros()

In [127]:
# create 1D array 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [128]:
# create 2d array
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [129]:
# create 3D zero matrix 
print(np.zeros((3,3,3)))
print(type( np.zeros((3,3,3))))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
<class 'numpy.ndarray'>


### create  ndarray object using ones()

In [130]:
# 1D Ones matrix 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [131]:
# 2D Ones matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [132]:
# 3d ones matrix 
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### create ndarray  object using linspace()

In [133]:
# 1D array 
# Syntax :- 
#             np.linspace(start , stop , num , endpoint , retstep, dtype)
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [134]:
np.linspace(1,100,6).reshape(2,3)

array([[  1. ,  20.8,  40.6],
       [ 60.4,  80.2, 100. ]])

In [135]:
np.linspace(2,99,12,endpoint=False).reshape((3,2,2))

array([[[ 2.        , 10.08333333],
        [18.16666667, 26.25      ]],

       [[34.33333333, 42.41666667],
        [50.5       , 58.58333333]],

       [[66.66666667, 74.75      ],
        [82.83333333, 90.91666667]]])

### create ndarry object using full()

  This function is used for building a matrix by specifying fill value either 1-D , 2-D , or N-D 

         Syntax :- 
                     varname = numpy.full(shape,fill_value , dtype )

In [136]:
arr = np.full(5,8)
arr

array([8, 8, 8, 8, 8])

In [137]:
# 2D array
arr = np.full((2,3),6)
arr

array([[6, 6, 6],
       [6, 6, 6]])

In [138]:
# 3D array
arr = np.full((3,3,3),3)
arr

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])

### Create ndarry object using identity()


    This function always build identity or unit matrix 
            syntax :- 
                     varname = numpy.identity(N,dtype)

                     Here N represents N*N matrix 

In [139]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [140]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### create ndarry object using eye()

   The eye() function is used to create a 2-D array with ones on the diagonal and zeros elsewhere.
   
          Syntax :- 
                       numpy.eye(N, M= None , k=0, dtype)
                       N = number of rows in the output
                       M = number of columns in the output . It None defaults to N
                       K = Index of the diagonal : 0 (the default) refers to the main diagonal , a positive value refers to an upper main diagonal , and a negative value to a lower diagonal  

In [141]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [142]:
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [143]:
np.eye(5,6,2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [144]:
np.eye(5,6,-2)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [145]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### Create ndarray object using hstack()

 Syntax :-    Varname :- numpy.hstack((ndaaryobj1),(ndarrayobj2)) 

 the function  numpy.hstack(tup) takes arguments as tuple which include matrix's/arrays horizontally which have the same number of rows . The hstack returns an ndarray 
              

In [146]:
arr1 = [1,2,3,4,5]
arr2 = [6,7,8,9,10]
np.hstack((arr1,arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.arange(10,20).reshape(2,5)
print("array 1 :- \n",arr1)
print("array 2 :- \n",arr2)
print("After hstack :- \n", np.hstack((arr1,arr2)))

array 1 :- 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array 2 :- 
 [[10 11 12 13 14]
 [15 16 17 18 19]]
After hstack :- 
 [[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


In [148]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.arange(10,20).reshape(2,5)
arr3 = np.arange(20,30).reshape(2,5)
print("array 1 :- \n",arr1)
print("array 2 :- \n",arr2)
print("array 3 :-\n",arr3)
print("After hstack :- \n", np.hstack((arr1,arr2,arr3)))

array 1 :- 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array 2 :- 
 [[10 11 12 13 14]
 [15 16 17 18 19]]
array 3 :-
 [[20 21 22 23 24]
 [25 26 27 28 29]]
After hstack :- 
 [[ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24]
 [ 5  6  7  8  9 15 16 17 18 19 25 26 27 28 29]]


### Create ndarray object using vsatck()

   Synatx :-  numpy.vstack((ndarray1,ndarray2,__ , ndarrayn))

   The function numpy.vstack(tup) takes arguments as tuple which include matrix,s/array . The vstack function combines the two or  more matrix / arrays . vertically which have the same number of columns . The vstack returns an ndarray

In [149]:
arr1 = [1,2,3,4,5]
arr2 = [6,7,8,9,10]
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [150]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.arange(10,20).reshape(2,5)
print("array 1 :- \n",arr1)
print("array 2 :- \n",arr2)
print("After vstack :- \n", np.vstack((arr1,arr2)))

array 1 :- 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array 2 :- 
 [[10 11 12 13 14]
 [15 16 17 18 19]]
After vstack :- 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [151]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.arange(10,20).reshape(2,5)
arr3 = np.arange(20,30).reshape(2,5)
print("array 1 :- \n",arr1)
print("array 2 :- \n",arr2)
print("array 3 :-\n",arr3)
print("After vstack :- \n", np.vstack((arr1,arr2,arr3)))

array 1 :- 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array 2 :- 
 [[10 11 12 13 14]
 [15 16 17 18 19]]
array 3 :-
 [[20 21 22 23 24]
 [25 26 27 28 29]]
After vstack :- 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


## Random module in numpy 

The purpose of random module is that "To generate random values for various applications development like otps , captcha code etcs.

    Random module of numpy contains the following functions 
                            
                               1. randint()
                               2. rand()
                               3. uniform()
                               4. randn()
                               5. normal()
                               6. shuffle()
                               7. choice()

In [152]:
import random 

In [153]:
np.random.randint(10)

3

In [154]:
np.random.randint(10,20)

16

In [155]:
np.random.randint(10,200,5)

array([ 98, 146, 119,  79, 123], dtype=int32)

In [156]:
np.random.rand(10)

array([0.120084  , 0.3986895 , 0.35870939, 0.99016718, 0.79624988,
       0.11459595, 0.91918504, 0.62199564, 0.52017279, 0.71753498])

In [157]:
np.random.rand(3,2)

array([[0.37375663, 0.91575292],
       [0.71541003, 0.6675974 ],
       [0.66296907, 0.20223436]])

In [158]:
np.random.rand(3,2,2)

array([[[0.85505233, 0.71787416],
        [0.49428133, 0.46577763]],

       [[0.87638166, 0.81284134],
        [0.81949139, 0.95481682]],

       [[0.85041503, 0.04717485],
        [0.95123705, 0.93540036]]])

In [159]:
np.random.uniform()

0.061950784999934116

In [160]:
np.random.uniform(10,20)

11.353465959664485

In [161]:
np.random.uniform(1,99,5)

array([64.72960335, 18.5218209 , 75.85440044, 13.99218464, 50.00137086])

In [162]:
np.random.uniform(1,99,(2,3,3))

array([[[21.10858099, 48.67972219,  6.33500109],
        [77.98978757,  2.18782882, 55.25724852],
        [34.14270435, 78.89122902,  3.76914213]],

       [[63.12443246, 91.63881068, 31.17094577],
        [69.32554419, 31.74534778, 94.56320631],
        [74.61472734, 71.08111661, 82.35925431]]])

In [163]:
np.random.randn()

-0.5036344500025094

In [164]:
np.random.randn(10)

array([-1.32793389,  1.3908301 , -0.84899138,  0.65590723, -0.75426325,
       -2.10742526, -0.35138188,  0.42590668,  0.82057774,  0.49561758])

In [165]:
np.random.randn(2,2)

array([[0.98236283, 0.09370438],
       [0.35772553, 0.1204463 ]])

In [166]:
arr = np.arange(10)
print("Array 1 :- ", arr)
np.random.shuffle(arr)
print("after suffling array 1:- " , arr)

Array 1 :-  [0 1 2 3 4 5 6 7 8 9]
after suffling array 1:-  [7 1 4 6 9 0 8 5 2 3]


In [167]:
arr = np.arange(100)
np.random.choice(arr)

np.int64(76)

### Numpy indexing 

In [168]:
arr = np.random.randn(3,3,3)
arr

array([[[ 1.07396667, -0.96958479, -1.35934037],
        [ 0.74923198, -1.79207135, -0.30497551],
        [-2.13001893,  0.86876468,  1.45899116]],

       [[-0.56495034, -1.71027231,  0.44721542],
        [ 0.35708191,  0.09485324,  1.56361173],
        [-0.77427629,  0.3168149 ,  0.03481178]],

       [[-0.14048956, -0.26668673,  0.67683555],
        [-0.88221052, -0.38967208,  1.37806807],
        [ 0.84021937, -0.26940206,  0.40943935]]])

In [169]:
arr[1]


array([[-0.56495034, -1.71027231,  0.44721542],
       [ 0.35708191,  0.09485324,  1.56361173],
       [-0.77427629,  0.3168149 ,  0.03481178]])

In [170]:
arr[0]

array([[ 1.07396667, -0.96958479, -1.35934037],
       [ 0.74923198, -1.79207135, -0.30497551],
       [-2.13001893,  0.86876468,  1.45899116]])

In [171]:
arr[0][1]

array([ 0.74923198, -1.79207135, -0.30497551])

In [172]:
arr[0][1][1]

np.float64(-1.7920713508246053)

In [173]:
arr[1,1,1]

np.float64(0.09485324348525151)

In [174]:
arr[1]

array([[-0.56495034, -1.71027231,  0.44721542],
       [ 0.35708191,  0.09485324,  1.56361173],
       [-0.77427629,  0.3168149 ,  0.03481178]])

### numpy slicing 

In [175]:
arr2 = np.arange(30).reshape((3,2,5))

In [176]:
arr2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [177]:
arr2[1]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [178]:
arr2[1][0]

array([10, 11, 12, 13, 14])

In [179]:
arr2[1][0][0:2]

array([10, 11])

In [180]:
arr2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [181]:
arr2[1]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [182]:
arr2[1][0:,3:]

array([[13, 14],
       [18, 19]])

In [183]:
arr2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [184]:
arr2[0:1,1:,1:4]

array([[[6, 7, 8]]])

### Advance Indexing and slicing 

In [185]:
arr = np.array([10,20,30,40,50,60])

In [186]:
arr

array([10, 20, 30, 40, 50, 60])

In [187]:
rind = [1,3,4]
arr[rind]

array([20, 40, 50])

In [188]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [189]:
rind = [0,1]
cind = [2,3]
arr[rind,cind]

array([2, 8])

In [190]:
rind = [0,0,1,1]
cind = [1,2,1,2]
arr[rind,cind]

array([1, 2, 6, 7])

In [191]:
# 3D array 
arr3 = np.arange(30).reshape(3,2,5)
arr3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [192]:
mind = [0,2]
rind = [1,0]
cind = [0,0]
arr3[mind,rind,cind]

array([ 5, 20])

### Filtering numpy array

For filtering the data , we have two functions . They are 
    
                                     1. where()
                                     2. extract()

## where()

The where() function allows us to filter an array based on a given condition . 
 
     Syntax :-     np.where(condition , x, y)