# NUMPY


Numpy is a fundamental library for scientific computing in python . It provides supports for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [1]:
import numpy as np

##  Number of approaches to create an object of ndarray

To create an object of ndarray . We have many approaches 

                    1. array()
                    2. arange()
                    3. zeros()
                    4. ones()
                    5. full()
                    6. linspace()
                    7. eye()
                    8. identity()
                    9. hsatck()
                    10. vstack()

## ndarray object attributes 

 Here  ndarray object contains the following attributes 
 
                  1. dtype
                  2. ndim 
                  3. shape
                  4. size
                  5. itemsize

### create ndarry object using array()

In [2]:
# create 1D array 
arr1 = np.array([1,2,3,4,5])
print("*"*50)
print("Array 1:- " , arr1)
print("Data Type of array 1:- " , arr1.dtype) 
print("Dimension of array 1:- ", arr1.ndim )
print("Size of array 1 :- ", arr1.size)
print("Item size of array1 :-" , arr1.itemsize)
print("*"*50)

**************************************************
Array 1:-  [1 2 3 4 5]
Data Type of array 1:-  int64
Dimension of array 1:-  1
Size of array 1 :-  5
Item size of array1 :- 8
**************************************************


In [3]:
# create 2D array 
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("*"*50)
print("Array 1:- \n " , arr1)
print("Data Type of array 1:- " , arr1.dtype) 
print("Dimension of array 1:- ", arr1.ndim )
print("Size of array 1 :- ", arr1.size)
print("Item size of array1 :-" , arr1.itemsize)
print("*"*50)

**************************************************
Array 1:- 
  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Data Type of array 1:-  int64
Dimension of array 1:-  2
Size of array 1 :-  10
Item size of array1 :- 8
**************************************************


In [4]:
# create 3D array 
arr1 = np.array([[[1,2,3,4,5],[6,7,8,9,10]] , [[10,20,30,40,50],[60,70,80,90,100]]])
print("*"*50)
print("Array 1:- \n " , arr1)
print("Data Type of array 1:- " , arr1.dtype) 
print("Dimension of array 1:- ", arr1.ndim )
print("Size of array 1 :- ", arr1.size)
print("Item size of array1 :-" , arr1.itemsize)
print("*"*50)

**************************************************
Array 1:- 
  [[[  1   2   3   4   5]
  [  6   7   8   9  10]]

 [[ 10  20  30  40  50]
  [ 60  70  80  90 100]]]
Data Type of array 1:-  int64
Dimension of array 1:-  3
Size of array 1 :-  20
Item size of array1 :- 8
**************************************************


### Create ndarray object using arange()

In [5]:
# create 1d array 
arr2 = np.arange(10)
print("*"*50)
print("Array 2:- \n " , arr2)
print("Data Type of array 2:- " , arr2.dtype) 
print("Dimension of array 2:- ", arr2.ndim )
print("Size of array 2 :- ", arr2.size)
print("Item size of array 2 :-" , arr2.itemsize)
print("*"*50)

**************************************************
Array 2:- 
  [0 1 2 3 4 5 6 7 8 9]
Data Type of array 2:-  int64
Dimension of array 2:-  1
Size of array 2 :-  10
Item size of array 2 :- 8
**************************************************


In [6]:
# create 2d array 
arr2 = np.arange(10).reshape(2,5)
print("*"*50)
print("Array 2:- \n " , arr2)
print("Data Type of array 2:- " , arr2.dtype) 
print("Dimension of array 2:- ", arr2.ndim )
print("Size of array 2 :- ", arr2.size)
print("Item size of array 2 :-" , arr2.itemsize)
print("*"*50)

**************************************************
Array 2:- 
  [[0 1 2 3 4]
 [5 6 7 8 9]]
Data Type of array 2:-  int64
Dimension of array 2:-  2
Size of array 2 :-  10
Item size of array 2 :- 8
**************************************************


In [7]:
# create 3d array 
arr2 = np.arange(10,100,3).reshape(3,2,5)
print("*"*50)
print("Array 2:- \n " , arr2)
print("Data Type of array 2:- " , arr2.dtype) 
print("Dimension of array 2:- ", arr2.ndim )
print("Size of array 2 :- ", arr2.size)
print("Item size of array 2 :-" , arr2.itemsize)
print("*"*50)

**************************************************
Array 2:- 
  [[[10 13 16 19 22]
  [25 28 31 34 37]]

 [[40 43 46 49 52]
  [55 58 61 64 67]]

 [[70 73 76 79 82]
  [85 88 91 94 97]]]
Data Type of array 2:-  int64
Dimension of array 2:-  3
Size of array 2 :-  30
Item size of array 2 :- 8
**************************************************


### Create ndarray object using zeros()

In [8]:
# create 1D array 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
# create 2d array
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
# create 3D zero matrix 
print(np.zeros((3,3,3)))
print(type( np.zeros((3,3,3))))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
<class 'numpy.ndarray'>


### create  ndarray object using ones()

In [11]:
# 1D Ones matrix 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
# 2D Ones matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# 3d ones matrix 
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### create ndarray  object using linspace()

In [14]:
# 1D array 
# Syntax :- 
#             np.linspace(start , stop , num , endpoint , retstep, dtype)
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [15]:
np.linspace(1,100,6).reshape(2,3)

array([[  1. ,  20.8,  40.6],
       [ 60.4,  80.2, 100. ]])

In [16]:
np.linspace(2,99,12,endpoint=False).reshape((3,2,2))

array([[[ 2.        , 10.08333333],
        [18.16666667, 26.25      ]],

       [[34.33333333, 42.41666667],
        [50.5       , 58.58333333]],

       [[66.66666667, 74.75      ],
        [82.83333333, 90.91666667]]])

### create ndarry object using full()

  This function is used for building a matrix by specifying fill value either 1-D , 2-D , or N-D 

         Syntax :- 
                     varname = numpy.full(shape,fill_value , dtype )

In [17]:
arr = np.full(5,8)
arr

array([8, 8, 8, 8, 8])

In [18]:
# 2D array
arr = np.full((2,3),6)
arr

array([[6, 6, 6],
       [6, 6, 6]])

In [19]:
# 3D array
arr = np.full((3,3,3),3)
arr

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])

### Create ndarry object using identity()


    This function always build identity or unit matrix 
            syntax :- 
                     varname = numpy.identity(N,dtype)

                     Here N represents N*N matrix 

In [20]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### create ndarry object using eye()

   The eye() function is used to create a 2-D array with ones on the diagonal and zeros elsewhere.
   
          Syntax :- 
                       numpy.eye(N, M= None , k=0, dtype)
                       N = number of rows in the output
                       M = number of columns in the output . It None defaults to N
                       K = Index of the diagonal : 0 (the default) refers to the main diagonal , a positive value refers to an upper main diagonal , and a negative value to a lower diagonal  

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [24]:
np.eye(5,6,2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.eye(5,6,-2)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [26]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### Create ndarray object using hstack()

 Syntax :-    Varname :- numpy.hstack((ndaaryobj1),(ndarrayobj2)) 

 the function  numpy.hstack(tup) takes arguments as tuple which include matrix's/arrays horizontally which have the same number of rows . The hstack returns an ndarray 
              

In [27]:
arr1 = [1,2,3,4,5]
arr2 = [6,7,8,9,10]
np.hstack((arr1,arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.arange(10,20).reshape(2,5)
print("array 1 :- \n",arr1)
print("array 2 :- \n",arr2)
print("After hstack :- \n", np.hstack((arr1,arr2)))

array 1 :- 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array 2 :- 
 [[10 11 12 13 14]
 [15 16 17 18 19]]
After hstack :- 
 [[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


In [29]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.arange(10,20).reshape(2,5)
arr3 = np.arange(20,30).reshape(2,5)
print("array 1 :- \n",arr1)
print("array 2 :- \n",arr2)
print("array 3 :-\n",arr3)
print("After hstack :- \n", np.hstack((arr1,arr2,arr3)))

array 1 :- 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array 2 :- 
 [[10 11 12 13 14]
 [15 16 17 18 19]]
array 3 :-
 [[20 21 22 23 24]
 [25 26 27 28 29]]
After hstack :- 
 [[ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24]
 [ 5  6  7  8  9 15 16 17 18 19 25 26 27 28 29]]


### Create ndarray object using vsatck()

   Synatx :-  numpy.vstack((ndarray1,ndarray2,__ , ndarrayn))

   The function numpy.vstack(tup) takes arguments as tuple which include matrix,s/array . The vstack function combines the two or  more matrix / arrays . vertically which have the same number of columns . The vstack returns an ndarray

In [30]:
arr1 = [1,2,3,4,5]
arr2 = [6,7,8,9,10]
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.arange(10,20).reshape(2,5)
print("array 1 :- \n",arr1)
print("array 2 :- \n",arr2)
print("After vstack :- \n", np.vstack((arr1,arr2)))

array 1 :- 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array 2 :- 
 [[10 11 12 13 14]
 [15 16 17 18 19]]
After vstack :- 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [32]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.arange(10,20).reshape(2,5)
arr3 = np.arange(20,30).reshape(2,5)
print("array 1 :- \n",arr1)
print("array 2 :- \n",arr2)
print("array 3 :-\n",arr3)
print("After vstack :- \n", np.vstack((arr1,arr2,arr3)))

array 1 :- 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array 2 :- 
 [[10 11 12 13 14]
 [15 16 17 18 19]]
array 3 :-
 [[20 21 22 23 24]
 [25 26 27 28 29]]
After vstack :- 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


## Random module in numpy 

The purpose of random module is that "To generate random values for various applications development like otps , captcha code etcs.

    Random module of numpy contains the following functions 
                            
                               1. randint()
                               2. rand()
                               3. uniform()
                               4. randn()
                               5. normal()
                               6. shuffle()
                               7. choice()

In [33]:
import random 

In [34]:
np.random.randint(10)

9

In [35]:
np.random.randint(10,20)

17

In [36]:
np.random.randint(10,200,5)

array([ 80,  34,  19, 107, 152], dtype=int32)

In [37]:
np.random.rand(10)

array([0.21321355, 0.80911342, 0.37089067, 0.03244346, 0.8882786 ,
       0.18544858, 0.88427126, 0.26648755, 0.27972812, 0.66928471])

In [38]:
np.random.rand(3,2)

array([[0.25767863, 0.95227463],
       [0.91321716, 0.70928234],
       [0.19869836, 0.96472106]])

In [39]:
np.random.rand(3,2,2)

array([[[0.69506744, 0.07490748],
        [0.56209628, 0.58072563]],

       [[0.61748315, 0.87639552],
        [0.97873323, 0.29467089]],

       [[0.59665542, 0.60227139],
        [0.92191589, 0.60818168]]])

In [40]:
np.random.uniform()

0.9706895187805905

In [41]:
np.random.uniform(10,20)

13.352392496295305

In [42]:
np.random.uniform(1,99,5)

array([68.59108459, 58.72326304, 26.80672889, 61.3698859 , 78.34959592])

In [43]:
np.random.uniform(1,99,(2,3,3))

array([[[ 4.40521462, 39.1307933 , 80.95036039],
        [75.35762487, 98.58766221, 39.74496477],
        [ 4.62453247, 27.64045198, 45.14231851]],

       [[13.1991315 , 83.23830318,  2.84449527],
        [66.33839533, 94.40934799, 87.73986089],
        [52.22652173, 92.65938447, 60.50070729]]])

In [44]:
np.random.randn()

0.9789860557190516

In [45]:
np.random.randn(10)

array([-0.32971285, -1.21958116, -0.73591273,  0.61248538, -0.67657191,
       -0.35083741,  1.23187514,  2.18516987, -1.50749849, -0.0079298 ])

In [46]:
np.random.randn(2,2)

array([[-0.6281589 , -1.64518827],
       [-0.39216778,  0.59636461]])

In [47]:
arr = np.arange(10)
print("Array 1 :- ", arr)
np.random.shuffle(arr)
print("after suffling array 1:- " , arr)

Array 1 :-  [0 1 2 3 4 5 6 7 8 9]
after suffling array 1:-  [0 5 7 9 8 6 2 3 1 4]


In [48]:
arr = np.arange(100)
np.random.choice(arr)

np.int64(42)

### Numpy indexing 

In [49]:
arr = np.random.randn(3,3,3)
arr

array([[[-1.49693908, -0.55720337, -1.02632943],
        [-0.26896375,  0.77649791, -0.049346  ],
        [ 1.4794267 , -0.67215199,  1.03430138]],

       [[-0.14438912, -0.81808069, -0.51402367],
        [ 1.05790702,  0.54952562, -1.76049761],
        [ 0.49934356,  0.88447852,  0.85991052]],

       [[-0.17091299, -0.40547426,  0.24945687],
        [-1.02107851,  0.18499498,  0.21670305],
        [ 2.54699475, -0.72706689, -0.99542402]]])

In [50]:
arr[1]


array([[-0.14438912, -0.81808069, -0.51402367],
       [ 1.05790702,  0.54952562, -1.76049761],
       [ 0.49934356,  0.88447852,  0.85991052]])

In [51]:
arr[0]

array([[-1.49693908, -0.55720337, -1.02632943],
       [-0.26896375,  0.77649791, -0.049346  ],
       [ 1.4794267 , -0.67215199,  1.03430138]])

In [52]:
arr[0][1]

array([-0.26896375,  0.77649791, -0.049346  ])

In [53]:
arr[0][1][1]

np.float64(0.7764979132127552)

In [54]:
arr[1,1,1]

np.float64(0.5495256234850585)

In [55]:
arr[1]

array([[-0.14438912, -0.81808069, -0.51402367],
       [ 1.05790702,  0.54952562, -1.76049761],
       [ 0.49934356,  0.88447852,  0.85991052]])

### numpy slicing 

In [56]:
arr2 = np.arange(30).reshape((3,2,5))

In [57]:
arr2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [58]:
arr2[1]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
arr2[1][0]

array([10, 11, 12, 13, 14])

In [60]:
arr2[1][0][0:2]

array([10, 11])

In [61]:
arr2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [62]:
arr2[1]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
arr2[1][0:,3:]

array([[13, 14],
       [18, 19]])

In [64]:
arr2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [65]:
arr2[0:1,1:,1:4]

array([[[6, 7, 8]]])

### Advance Indexing and slicing 

In [66]:
arr = np.array([10,20,30,40,50,60])

In [67]:
arr

array([10, 20, 30, 40, 50, 60])

In [68]:
rind = [1,3,4]
arr[rind]

array([20, 40, 50])

In [69]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
rind = [0,1]
cind = [2,3]
arr[rind,cind]

array([2, 8])

In [71]:
rind = [0,0,1,1]
cind = [1,2,1,2]
arr[rind,cind]

array([1, 2, 6, 7])

In [72]:
# 3D array 
arr3 = np.arange(30).reshape(3,2,5)
arr3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [73]:
mind = [0,2]
rind = [1,0]
cind = [0,0]
arr3[mind,rind,cind]

array([ 5, 20])

### Filtering numpy array

For filtering the data , we have two functions . They are 
    
                                     1. where()
                                     2. extract()

## where()

The where() function allows us to filter an array based on a given condition . 
 
     Syntax :-     np.where(condition , x, y)

In [74]:
a = np.array([1,2,3,4,5,6,7,8])
# values greater than 5 
np.where(a>5,a,'Nl')

array(['Nl', 'Nl', 'Nl', 'Nl', 'Nl', '6', '7', '8'], dtype='<U21')

In [75]:
a = np.arange(100)
# values divide by 2
np.where(a%2==0, a, "None")

array(['0', 'None', '2', 'None', '4', 'None', '6', 'None', '8', 'None',
       '10', 'None', '12', 'None', '14', 'None', '16', 'None', '18',
       'None', '20', 'None', '22', 'None', '24', 'None', '26', 'None',
       '28', 'None', '30', 'None', '32', 'None', '34', 'None', '36',
       'None', '38', 'None', '40', 'None', '42', 'None', '44', 'None',
       '46', 'None', '48', 'None', '50', 'None', '52', 'None', '54',
       'None', '56', 'None', '58', 'None', '60', 'None', '62', 'None',
       '64', 'None', '66', 'None', '68', 'None', '70', 'None', '72',
       'None', '74', 'None', '76', 'None', '78', 'None', '80', 'None',
       '82', 'None', '84', 'None', '86', 'None', '88', 'None', '90',
       'None', '92', 'None', '94', 'None', '96', 'None', '98', 'None'],
      dtype='<U21')

In [76]:
a = np.array([10,20,30,40])
x = np.array([1,2,3,4])
y = np.array([100,200,300,400])
np.where(a%20==0, x,y)

array([100,   2, 300,   4])

In [77]:
## filtering with multiple criteria 
a = np.array([1,2,3,4])
criteria = (a<2)|(a>3)
np.where(criteria, 0, a)

array([0, 2, 3, 0])

## extract()

The extract( ) function provides a more direct way to filter arrays . It selects elements based on a condition and returns only those elements , rather than a new array with the same shape . 
  
   syntax :- np.extract(condition , arr)

In [78]:
a = np.arange(100)
np.extract(a%2==0,a)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [79]:
a = np.array([1,2,3,4])
criteria = (a<2)|(a>3)
np.extract(criteria, a)

array([1, 4])

In [80]:
### practical use of where() and extract()
data = np.array([1,2,None,3,4])
## Replace None with zero 
np.where(data==None, 0, data )

array([1, 2, 0, 3, 4], dtype=object)

In [81]:
## filter missing value 
data = np.array([1,2,None,3,4]) 
np.extract(data!=None,data)


array([1, 2, 3, 4], dtype=object)

### Enumerate iteration using ndenumerate()

In [82]:
arr = np.array([1,2,3])
for idx , x in np.ndenumerate(arr):
    print(idx , x)

(0,) 1
(1,) 2
(2,) 3


### comaprision 

In [83]:
arr1 = np.array([1,4,2,52,3])
arr2 = np.array([45,1,2,48,9])
print(np.greater(arr1,arr2))
print(np.less(arr1,arr2))
print(np.equal(arr1,arr2))
print(np.greater_equal(arr1,arr2))
print(np.less_equal(arr1,arr2))
print(np.not_equal(arr1,arr2))

[False  True False  True False]
[ True False False False  True]
[False False  True False False]
[False  True  True  True False]
[ True False  True False  True]
[ True  True False  True  True]


### array splitting 

                   1. np.split()
                   2. np.array_split()
                   3. np.vsplit()
                   4. np.hsplit()
                   5. np.dsplit()

In [84]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [85]:
np.split(arr1,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [86]:
np.array_split(arr1,3)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [87]:
arr2 = np.arange(10).reshape(2,5)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [88]:
np.vsplit(arr2, 2)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

In [89]:
arr3 = np.arange(4).reshape(2,2)
print(arr3)

[[0 1]
 [2 3]]


In [90]:
np.hsplit(arr3,2)

[array([[0],
        [2]]),
 array([[1],
        [3]])]

In [91]:
arr4 = np.arange(12).reshape(3,2,2)
print(arr4)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [92]:
np.dsplit(arr4,2)

[array([[[ 0],
         [ 2]],
 
        [[ 4],
         [ 6]],
 
        [[ 8],
         [10]]]),
 array([[[ 1],
         [ 3]],
 
        [[ 5],
         [ 7]],
 
        [[ 9],
         [11]]])]

### ARITHMATIC OR MATRIX OPERATIONS

In [93]:
a1 = np.array([1,2,3,4,5,6,7])
a2 = np.array([2,1,3,4,2,4,5])
print('array 1 :- ' , a1)
print('array 2 :- ' , a2)
print("Addition :- " , np.add(a1,a2))
print("Subtraction :-" ,np.subtract(a1,a2))
print("Multiplication :-" ,np.multiply(a1,a2))
print("Dot product  :- " , np.dot(a1,a2) )
print("Division :- " , np.divide(a1,a2))
print("Floor division :- " , np.floor_divide(a1,a2))
print("Reaminder :- " , np.mod(a1,a2))
print("Power :- " , np.power(a1,a2))



array 1 :-  [1 2 3 4 5 6 7]
array 2 :-  [2 1 3 4 2 4 5]
Addition :-  [ 3  3  6  8  7 10 12]
Subtraction :- [-1  1  0  0  3  2  2]
Multiplication :- [ 2  2  9 16 10 24 35]
Dot product  :-  98
Division :-  [0.5 2.  1.  1.  2.5 1.5 1.4]
Floor division :-  [0 2 1 1 2 1 1]
Reaminder :-  [1 0 0 0 1 2 2]
Power :-  [    1     2    27   256    25  1296 16807]


### unique values 

In [94]:
arr1 = np.array([11,1,1,2,1,2,1,2,3,34,2,45,23,23,21,45,232])
print(arr1)
print("Unique element array :-" ,np.unique(arr1))

[ 11   1   1   2   1   2   1   2   3  34   2  45  23  23  21  45 232]
Unique element array :- [  1   2   3  11  21  23  34  45 232]


In [95]:
element , count = np.unique(arr1, return_counts=True)
for i , j in zip(element , count):
    print(i ,"occur" , j ,"Times")

1 occur 4 Times
2 occur 4 Times
3 occur 1 Times
11 occur 1 Times
21 occur 1 Times
23 occur 2 Times
34 occur 1 Times
45 occur 2 Times
232 occur 1 Times


In [96]:
### unique values and their first index 
element , indx = np.unique(arr1, return_index=True)
for element , index in zip(element , indx):
    print(element , "At index" , index)

1 At index 1
2 At index 3
3 At index 8
11 At index 0
21 At index 14
23 At index 12
34 At index 9
45 At index 11
232 At index 16


### numpy:- statistical opeartions 

In [97]:
arr1 = np.random.randn(100)
print(arr1)

[ 6.20601291e-01  1.75654941e+00  1.42633396e-01  7.78385724e-01
  7.71149669e-01  7.09956976e-02  1.04088810e+00 -7.85498068e-01
  9.49091543e-01 -8.46025752e-02  6.71308167e-01 -9.12560090e-01
 -9.86241626e-01 -6.51752935e-01 -4.03062628e-01  1.74775173e+00
  9.50391360e-01  1.01918073e+00 -1.22606954e-01  6.68409863e-01
  4.76475574e-01  5.92600725e-01 -1.37934456e+00  1.97416968e+00
 -5.64363030e-01 -5.82191863e-01 -8.71449696e-01 -2.28333133e-01
 -8.99145075e-02  7.18169618e-01 -6.81213564e-01 -1.56755543e+00
  1.22866608e+00  5.01652040e-01 -2.14339827e+00  9.94058852e-01
  7.71026011e-01 -9.18527863e-01  3.62214536e-03  1.84564642e+00
 -3.28178411e-01  1.07332896e+00  3.80580405e-01 -2.88051157e-01
 -9.06377456e-04 -1.70320414e+00 -4.33728888e-01 -5.51730536e-01
  3.86170973e-01  2.32827892e-01  3.24129054e-01 -1.03903958e+00
 -8.24332372e-01  7.28677996e-01 -1.11236250e+00  2.09056901e-01
 -1.52217930e-01 -8.97275559e-02 -1.01742598e-01  1.25258275e+00
  1.09646992e+00 -2.00933

In [98]:
print("Max element :- " ,np.amax(arr1))
print("Min element :- " ,np.amin(arr1))
print("Mean of array :- " ,np.mean(arr1))
print("Median of array :- " , np.median(arr1))
print("Variance of array :- " , np.var(arr1))
print("Standard devaition of array :- ", np.std(arr1))

Max element :-  1.9741696770025385
Min element :-  -2.248359186223199
Mean of array :-  0.03357239935149142
Median of array :-  0.0013578839537715262
Variance of array :-  0.8212507692411216
Standard devaition of array :-  0.9062288724384815


In [99]:

arr2 = np.array([1,2,1,3,4,5,2])
print("array2 :- ", arr2)
# adding 50 at end in arr2 
arr2=np.append(arr2, 50)
print("After adding a element :- " , arr2)


array2 :-  [1 2 1 3 4 5 2]
After adding a element :-  [ 1  2  1  3  4  5  2 50]


In [100]:
arr3 = np.arange(10)
print("array 3 :- " , arr3)
print("Size of array :- ", arr3.size)
# add 23 at index 3 
arr3 = np.insert(arr3, 3, 23)
print("After insertion :- " , arr3)
print("Size of array :- ", arr3.size)

array 3 :-  [0 1 2 3 4 5 6 7 8 9]
Size of array :-  10
After insertion :-  [ 0  1  2 23  3  4  5  6  7  8  9]
Size of array :-  11


In [101]:
# delete index 4 from arr3 
arr3 = np.delete(arr3 , 4)
print("New array :-" , arr3)
print("Size of array :- ", arr3.size)

New array :- [ 0  1  2 23  4  5  6  7  8  9]
Size of array :-  10


In [102]:
arr4 = np.arange(15).reshape(3,5)
print("Array 4 :- \n" , arr4  )

Array 4 :- 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [103]:
# delete column index 2 ,3 
arr4 =np.delete(arr4 , [2,3],axis=1)
print(arr4)

[[ 0  1  4]
 [ 5  6  9]
 [10 11 14]]


### copy() vs view()

In [104]:
arr1 = np.arange(10)
print("initial array :- ", arr1)
arr2 = arr1.copy()
print("Copy of array :- " , arr2)
arr1[0]=45
print("initial array :- ", arr1)
print("Copy of array :- " , arr2)

initial array :-  [0 1 2 3 4 5 6 7 8 9]
Copy of array :-  [0 1 2 3 4 5 6 7 8 9]
initial array :-  [45  1  2  3  4  5  6  7  8  9]
Copy of array :-  [0 1 2 3 4 5 6 7 8 9]


In [105]:
arr1 = np.arange(10,20)
print("initial array :- ", arr1)
arr2 = arr1.view()
print("view of array :- " , arr2)
arr1[0]=45
print("initial array :- ", arr1)
print("view of array :- " , arr2)
arr2[3]=23
print("initial array :- ", arr1)
print("view of array :- " , arr2)


initial array :-  [10 11 12 13 14 15 16 17 18 19]
view of array :-  [10 11 12 13 14 15 16 17 18 19]
initial array :-  [45 11 12 13 14 15 16 17 18 19]
view of array :-  [45 11 12 13 14 15 16 17 18 19]
initial array :-  [45 11 12 23 14 15 16 17 18 19]
view of array :-  [45 11 12 23 14 15 16 17 18 19]


In [106]:
print(arr1.base)

None


In [107]:
print(arr2.base)

[45 11 12 23 14 15 16 17 18 19]


### numpy :- flatten() and ravel()

In numpy , both the flatten() and ravel functions are used to convert multidimensional arrays into one - dimensional arrays . However , there are a few diffrences between these two functions . 


The flatten() function returns a copy of the array , while the ravel() functions returns a view of the original array whenever possible . A view is a reference to the original data  , whereas a  copy creates a new array with it,s own data 

In [108]:
arr3 = np.arange(8).reshape(2,2,2)
print("array :- \n ", arr3)
print("Dimension of arr3 :- " , arr3.ndim )

array :- 
  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Dimension of arr3 :-  3


In [109]:
# using flatten()
print("Original array :- \n ",arr3)
new_arr = arr3.flatten()
print("Flattened array :- ",new_arr)
new_arr[2]=7
print("Original array :- \n ",arr3)
print("Flattened array :- ",new_arr)

Original array :- 
  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Flattened array :-  [0 1 2 3 4 5 6 7]
Original array :- 
  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Flattened array :-  [0 1 7 3 4 5 6 7]


In [110]:
# using ravel()
print("Original array :- \n ",arr3)
new_arr = arr3.ravel()
print("raveled  array :- ",new_arr)
new_arr[2]=7
print("Original array :- \n ",arr3)
print("raveled  array :- ",new_arr)


Original array :- 
  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
raveled  array :-  [0 1 2 3 4 5 6 7]
Original array :- 
  [[[0 1]
  [7 3]]

 [[4 5]
  [6 7]]]
raveled  array :-  [0 1 7 3 4 5 6 7]


#### sorting in numpy 

In [111]:
 # sorting in 1D array 
arr = np.random.randn(10)
print("Original array :-" , arr)
print("Sorted array :- " , np.sort(arr))

Original array :- [-0.01695934  0.87422881 -1.55150327 -1.4978723   0.04889821 -1.87792886
  0.0162782  -0.43295392  1.84627762  0.44920064]
Sorted array :-  [-1.87792886 -1.55150327 -1.4978723  -0.43295392 -0.01695934  0.0162782
  0.04889821  0.44920064  0.87422881  1.84627762]


In [112]:
# soritng in 2D array 
arr = np.random.randn(10).reshape(2,5)
print("Original array :- \n" , arr)
print("Row wise sorted array :- \n" , np.sort(arr, axis = 1))
print("Column wise sorted array :- \n", np.sort(arr, axis =0))

Original array :- 
 [[-0.60090104 -0.9827539  -0.20362932 -1.48757059 -0.75277595]
 [-0.03401454 -0.18618165  0.93505783  0.53670982  0.33070725]]
Row wise sorted array :- 
 [[-1.48757059 -0.9827539  -0.75277595 -0.60090104 -0.20362932]
 [-0.18618165 -0.03401454  0.33070725  0.53670982  0.93505783]]
Column wise sorted array :- 
 [[-0.60090104 -0.9827539  -0.20362932 -1.48757059 -0.75277595]
 [-0.03401454 -0.18618165  0.93505783  0.53670982  0.33070725]]


In [113]:
# absolute values of array 
arr = np.random.randn(10)
print("original array :- " , arr)
print("absolute array :- " , np.absolute(arr))

original array :-  [ 1.48059784 -0.34100741 -0.16286945  0.06530972  0.52612119  0.2574669
 -1.24582399 -0.25492464  0.07871027  1.66673645]
absolute array :-  [1.48059784 0.34100741 0.16286945 0.06530972 0.52612119 0.2574669
 1.24582399 0.25492464 0.07871027 1.66673645]


In [114]:
# summation 0f array1 and array 2
arr1 = np.arange(10)
arr2 = np.arange(20,30)
print("array 1 :- ", arr1)
print("array 2 :- ", arr2)
print("Total sum of array 1 and array 2 elements :-" , np.sum([arr1,arr2]))

array 1 :-  [0 1 2 3 4 5 6 7 8 9]
array 2 :-  [20 21 22 23 24 25 26 27 28 29]
Total sum of array 1 and array 2 elements :- 290


In [115]:
# summation 0f array1 and array 2 on row basis 
arr1 = np.arange(10)
arr2 = np.arange(20,30)
print("array 1 :- ", arr1)
print("array 2 :- ", arr2)
print("Total sum of array 1 and array 2 elements along row side  :-" , np.sum([arr1,arr2], axis = 1))
print("Total sum of array 1 and array 2 elements along columns side  :-" , np.sum([arr1,arr2], axis = 0))


array 1 :-  [0 1 2 3 4 5 6 7 8 9]
array 2 :-  [20 21 22 23 24 25 26 27 28 29]
Total sum of array 1 and array 2 elements along row side  :- [ 45 245]
Total sum of array 1 and array 2 elements along columns side  :- [20 22 24 26 28 30 32 34 36 38]


In [116]:
## cummulative sum of array 1 elements 
arr1 = np.random.uniform(10,20,5)
print("Original array :- " , arr1)
print("Cummulative sum of array :- ", np.cumsum(arr1))

Original array :-  [16.96285924 18.6682153  19.55696946 11.95914629 19.37438692]
Cummulative sum of array :-  [16.96285924 35.63107454 55.188044   67.14719029 86.52157721]


In [117]:
## product of elements of array 1 
arr1 = np.random.uniform(1,10,5)
print("Original array :- " , arr1)
print("Product of array :- ", np.prod(arr1))

Original array :-  [3.49135335 8.67521075 6.63152226 9.72839654 6.14902092]
Product of array :-  12015.291331215674


In [118]:
### commulative product 
arr1 = np.random.uniform(1,10,5)
print("Original array :- " , arr1)
print("cummulative Product of array :- ", np.cumprod(arr1))


Original array :-  [5.99718853 4.51229285 6.95499013 4.26699184 4.90819618]
cummulative Product of array :-  [   5.99718853   27.06107094  188.20948133  803.08832109 3941.71503155]


### numpy rounding decimals 

                          1. trunc() or fix()
                          2. around()
                          3. floor()
                          4. ceil()

In [119]:
arr = np.random.uniform(10,100,5)
print("Original array :- " , arr)
print("Fixing zeroes :- " , np.fix(arr))
print("Fixing zeroes :- " , np.trunc(arr)) 
print("floor value of array :- " , np.floor(arr))  
print("ceil value of array :- " , np.ceil(arr))           

Original array :-  [99.32868024 28.48910631 94.33860946 79.97675363 97.0839913 ]
Fixing zeroes :-  [99. 28. 94. 79. 97.]
Fixing zeroes :-  [99. 28. 94. 79. 97.]
floor value of array :-  [99. 28. 94. 79. 97.]
ceil value of array :-  [100.  29.  95.  80.  98.]


In [120]:
## LCM 
num1 = 100
num2 = 25
print("LCM of {} and {} = {}" .format(num1,num2,np.lcm(num1,num2)))

LCM of 100 and 25 = 100


In [121]:
# LCM of all elements of array 1 
arr = np.arange(10,20)
print("Original array :-" , arr)
print("LCM OF array :- " , np.lcm.reduce(arr))

Original array :- [10 11 12 13 14 15 16 17 18 19]
LCM OF array :-  232792560


In [122]:
# GCD of elements 
num1 = 29 
num2 =90 
print("GCD of {} and {} = {}" .format(num1,num2,np.gcd(num1,num2)))

GCD of 29 and 90 = 1


In [123]:
num1 = 22 
num2 =90 
print("GCD of {} and {} = {}" .format(num1,num2,np.gcd(num1,num2)))

GCD of 22 and 90 = 2


In [124]:
# Finding gcd of all elemens of giving array 
arr = np.arange(10,20 )
print("Original array :- " , arr)
print("GCD of given array :- " , np.gcd.reduce(arr))

Original array :-  [10 11 12 13 14 15 16 17 18 19]
GCD of given array :-  1


### numpy linear algebra 

                        1. dot()            calculates  products of two arrays 
                        2. inner()          calculates inner product of array
                        3. outer()          calculates outers product of array
                        4. linalg.det()            calculate determinant of matrix 
                        5. solve()          solve linear matrix equations 
                        6. inv()            calculate the multiplicative inverse of the matrix 
                        7. trace()          calculates the sum of diagonals elements 

In [125]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(10,14).reshape(2,2)
print("array 1 : - \n" , arr1)
print("array 2 :- \n " , arr2)
print("Dot products :-\n " , np.dot(arr1,arr2))
print("Inner product :- \n" , np.inner(arr1,arr2))
print("Outer product :-\n ", np.outer(arr1,arr2) )
print("Dterminant of array 1:- " , np.linalg.det(arr1))
print("Inverse of array 1 :- \n ", np.linalg.inv(arr1))
print("Diagonal elements sum of array 1 :- " , np.trace(arr1))

array 1 : - 
 [[1 2]
 [3 4]]
array 2 :- 
  [[10 11]
 [12 13]]
Dot products :-
  [[34 37]
 [78 85]]
Inner product :- 
 [[32 38]
 [74 88]]
Outer product :-
  [[10 11 12 13]
 [20 22 24 26]
 [30 33 36 39]
 [40 44 48 52]]
Dterminant of array 1:-  -2.0000000000000004
Inverse of array 1 :- 
  [[-2.   1. ]
 [ 1.5 -0.5]]
Diagonal elements sum of array 1 :-  5


                                       THANK YOU 